contentColumnType: string(256)
fieldGroup: 312a90a8-ae56-4475-8172-73c676f379fc
handle: brand
instructions: ''
name: Brand
searchable: false
settings:
  byteLimit: null
  charLimit: 64
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
