contentColumnType: string(255)
fieldGroup: 24ff2309-b32b-411f-a560-8826f54eb00c
handle: instagram
instructions: ''
name: Instagram
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
