enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7da43cc4-f72d-4fe1-8ff4-0d53192f5d20:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
